spring:
  application:
    name: apizuul
server:
  port: 9001
zuul:
  routes:
    myProduct:
      path: /myProduct/**
      serviceId: product
  # 全部服务都可以传递cookie，忽略敏感头
  sensitive-headers:
 management:
  endpoints:
    web:
      exposure:
        include: "*"
